/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package paneles.Z_Compras;

import A_alertas.principal.ErrorAlert;
import A_alertas.principal.WarningAlertG;
import A_alertas.principal.WarningAlertP;
import A_tabla.EstiloTablaHeader;
import A_tabla.EstiloTablaRenderer;
import A_tabla.MyScrollbarUI;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.ListSelectionModel;
import javax.swing.border.EtchedBorder;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;


/**
 *
 * @author jona
 */
public class pnlCompras extends javax.swing.JPanel {

    /**
     * Creates new form pnlCompras
     */
    public pnlCompras() {
        initComponents();
        this.tabla.getTableHeader().setDefaultRenderer(new EstiloTablaHeader());
        this.tabla.setDefaultRenderer(Object.class, new EstiloTablaRenderer());
        this.tabla.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.getViewport().setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.getViewport().setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.getVerticalScrollBar().setUI(new MyScrollbarUI());
        jScrollPane1.getHorizontalScrollBar().setUI(new MyScrollbarUI());
        this.txtDescripcion.setLineWrap(true);
        Opciones.listar("");
        Opciones.totalGastos();
        
        this.tabla.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                if (tabla.getSelectedRow() != -1) {
                    int fila = tabla.getSelectedRow();
                    Opciones.extraerDescripcion(tabla.getValueAt(fila, 0).toString());
                }
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pnlmodificar = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pnlremover = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        pnlagregar = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        lblTotal1 = new javax.swing.JLabel();
        lblTotal2 = new javax.swing.JLabel();
        lblTotal3 = new javax.swing.JLabel();
        buscar = new app.bolivia.swing.JCTextField();
        jLabel2 = new javax.swing.JLabel();
        materialButtonCircle2 = new principal.MaterialButtonCircle();
        materialButtonCircle3 = new principal.MaterialButtonCircle();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(225, 225, 225));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("  Compras");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 60));

        jPanel12.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 60));

        pnlmodificar.setBackground(new java.awt.Color(225, 225, 225));
        pnlmodificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlmodificarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlmodificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlmodificarMouseExited(evt);
            }
        });
        pnlmodificar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("   Modificar");
        pnlmodificar.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 80, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Imagenes/modificar.PNG"))); // NOI18N
        pnlmodificar.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, 40));

        jPanel12.add(pnlmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, 60));

        pnlremover.setBackground(new java.awt.Color(225, 225, 225));
        pnlremover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlremoverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlremoverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlremoverMouseExited(evt);
            }
        });
        pnlremover.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Imagenes/menos.PNG"))); // NOI18N
        pnlremover.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 4, 40, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Eliminar");
        pnlremover.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 50, 20));

        jPanel12.add(pnlremover, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 80, 60));

        pnlagregar.setBackground(new java.awt.Color(225, 225, 225));
        pnlagregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlagregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlagregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlagregarMouseExited(evt);
            }
        });
        pnlagregar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("    Agregar");
        pnlagregar.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 80, 20));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Imagenes/mas.PNG"))); // NOI18N
        pnlagregar.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 41, 30));

        jPanel12.add(pnlagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, 60));

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 125, 620, 10));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tabla.setBackground(new java.awt.Color(204, 204, 204));
        tabla.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tabla.setForeground(new java.awt.Color(255, 255, 255));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Proveedor", "Fecha", "Total", "pdf"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabla.setDoubleBuffered(true);
        tabla.setRowHeight(20);
        tabla.setSelectionBackground(new java.awt.Color(0, 153, 255));
        tabla.getTableHeader().setReorderingAllowed(false);
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(0).setMinWidth(80);
            tabla.getColumnModel().getColumn(0).setPreferredWidth(80);
            tabla.getColumnModel().getColumn(0).setMaxWidth(80);
            tabla.getColumnModel().getColumn(1).setMinWidth(115);
            tabla.getColumnModel().getColumn(1).setPreferredWidth(115);
            tabla.getColumnModel().getColumn(1).setMaxWidth(115);
            tabla.getColumnModel().getColumn(2).setMinWidth(85);
            tabla.getColumnModel().getColumn(2).setPreferredWidth(85);
            tabla.getColumnModel().getColumn(2).setMaxWidth(85);
            tabla.getColumnModel().getColumn(3).setMinWidth(90);
            tabla.getColumnModel().getColumn(3).setPreferredWidth(90);
            tabla.getColumnModel().getColumn(3).setMaxWidth(90);
            tabla.getColumnModel().getColumn(4).setMinWidth(0);
            tabla.getColumnModel().getColumn(4).setPreferredWidth(0);
            tabla.getColumnModel().getColumn(4).setMaxWidth(0);
        }

        jScrollPane2.setBackground(new java.awt.Color(58, 159, 171));
        jScrollPane2.setBorder(null);
        jScrollPane2.setOpaque(false);

        txtDescripcion.setEditable(false);
        txtDescripcion.setBackground(new java.awt.Color(198, 202, 193));
        txtDescripcion.setColumns(20);
        txtDescripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        txtDescripcion.setRows(5);
        txtDescripcion.setBorder(null);
        txtDescripcion.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtDescripcion.setOpaque(false);
        jScrollPane2.setViewportView(txtDescripcion);

        lblTotal1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTotal1.setText("0.0");

        lblTotal2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotal2.setText("Total en Compras:");

        lblTotal3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotal3.setForeground(new java.awt.Color(153, 153, 153));
        lblTotal3.setText("Descripción de la Compra:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblTotal2)
                        .addGap(6, 6, 6)
                        .addComponent(lblTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblTotal3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal2))
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lblTotal3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 630, 430));

        buscar.setBorder(null);
        buscar.setForeground(new java.awt.Color(136, 0, 0));
        buscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buscar.setPlaceholder("BUSCAR");
        buscar.setSelectionColor(new java.awt.Color(102, 102, 102));
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                buscarKeyTyped(evt);
            }
        });
        jPanel1.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 140, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Imagenes/campo-buscar.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 210, -1));

        materialButtonCircle2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(materialButtonCircle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 50, 50));

        materialButtonCircle3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(materialButtonCircle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 50, 50));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 570));
    }// </editor-fold>//GEN-END:initComponents

    private void pnlmodificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlmodificarMouseEntered
        pnlmodificar.setBorder(new EtchedBorder(EtchedBorder.RAISED,Color.gray,Color.LIGHT_GRAY));
    }//GEN-LAST:event_pnlmodificarMouseEntered

    private void pnlmodificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlmodificarMouseExited
        pnlmodificar.setBorder(new EtchedBorder(EtchedBorder.RAISED,new java.awt.Color(225,225,225),new java.awt.Color(225,225,225)));
    }//GEN-LAST:event_pnlmodificarMouseExited

    private void pnlremoverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlremoverMouseEntered
        pnlremover.setBorder(new EtchedBorder(EtchedBorder.RAISED,Color.gray,Color.LIGHT_GRAY));
    }//GEN-LAST:event_pnlremoverMouseEntered

    private void pnlremoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlremoverMouseExited
        pnlremover.setBorder(new EtchedBorder(EtchedBorder.RAISED,new java.awt.Color(225,225,225),new java.awt.Color(225,225,225)));
    }//GEN-LAST:event_pnlremoverMouseExited

    private void pnlagregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlagregarMouseClicked
        Registro_Compra mp = new Registro_Compra(new JFrame(), true);
        mp.titulo.setText("Registrar Compras");
        mp.registrar.setText("Registrar");
        mp.setVisible(true);
    }//GEN-LAST:event_pnlagregarMouseClicked

    private void pnlagregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlagregarMouseEntered
        pnlagregar.setBorder(new EtchedBorder(EtchedBorder.RAISED,Color.gray,Color.LIGHT_GRAY));

    }//GEN-LAST:event_pnlagregarMouseEntered

    private void pnlagregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlagregarMouseExited
        pnlagregar.setBorder(new EtchedBorder(EtchedBorder.RAISED,new java.awt.Color(225,225,225),new java.awt.Color(225,225,225)));
    }//GEN-LAST:event_pnlagregarMouseExited

    private void buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarKeyReleased
        Opciones.listar(this.buscar.getText());
    }//GEN-LAST:event_buscarKeyReleased

    private void buscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarKeyTyped
        char letras = evt.getKeyChar();

        if (Character.isLowerCase(letras)) {
            String cad = ("" + letras).toUpperCase();
            letras = cad.charAt(0);
            evt.setKeyChar(letras);
        }
    }//GEN-LAST:event_buscarKeyTyped

    private void pnlremoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlremoverMouseClicked
        if (this.tabla.getRowCount() < 1) {
            ErrorAlert er = new ErrorAlert(new JFrame(), true);
            er.titulo.setText("Mensaje");
            er.msj.setText("No hay productos");
            er.msj1.setText("agregados a la venta");
            er.setVisible(true);
        } else {
            if (this.tabla.getSelectedRowCount() < 1) {
                ErrorAlert er = new ErrorAlert(new JFrame(), true);
                er.titulo.setText("Mensaje");
                er.msj.setText("Seleccione almenos un");
                er.msj1.setText("registro");
                er.setVisible(true);
            } else {
                int fila = this.tabla.getSelectedRow();
                WarningAlertG wa = new WarningAlertG(new JFrame(), true);
                wa.id.setText(this.tabla.getValueAt(fila, 0).toString());
                wa.titulo.setText("¿Esta Seguro?");
                wa.msj.setText("Se borrara permanentemente");
                wa.msj1.setText("un registro");
                wa.setVisible(true);
            }
        }
    }//GEN-LAST:event_pnlremoverMouseClicked

    private void pnlmodificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlmodificarMouseClicked
       if (this.tabla.getRowCount() < 1) {
            ErrorAlert er = new ErrorAlert(new JFrame(), true);
            er.titulo.setText("Mensaje");
            er.msj.setText("La tabla actualmente");
            er.msj1.setText("esta vacia");
            er.setVisible(true);
        } else {
            if (this.tabla.getSelectedRowCount() < 1) {
                ErrorAlert er = new ErrorAlert(new JFrame(), true);
                er.titulo.setText("Mensaje");
                er.msj.setText("Seleccione al menos un");
                er.msj1.setText("Registro");
                er.setVisible(true);
            } else {

                int fila = this.tabla.getSelectedRow();

                Registro_Compra mp = new Registro_Compra(new JFrame(), true);
                mp.id.setText(this.tabla.getValueAt(fila, 0).toString());
                mp.txtDescripcion.setText(this.txtDescripcion.getText());
                mp.txtDescripcion.setText(this.txtDescripcion.getText());
                //mp.Fecha.setCalendar(this.tabla.getValueAt(fila, 2).toString());
                mp.Proveedor.setSelectedItem(this.tabla.getValueAt(fila, 3).toString());
                mp.txtTotal.setText(this.tabla.getValueAt(fila, 4).toString());
                mp.txtRuta.setText(this.tabla.getValueAt(fila, 5).toString());
                mp.titulo.setText("Modificar Registro de Compra");
                mp.registrar.setText("Guardar");
                mp.setVisible(true);
            }
        }
    }//GEN-LAST:event_pnlmodificarMouseClicked

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
       
    }//GEN-LAST:event_tablaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static app.bolivia.swing.JCTextField buscar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JLabel lblTotal1;
    public static javax.swing.JLabel lblTotal2;
    public static javax.swing.JLabel lblTotal3;
    private principal.MaterialButtonCircle materialButtonCircle2;
    private principal.MaterialButtonCircle materialButtonCircle3;
    private javax.swing.JPanel pnlagregar;
    private javax.swing.JPanel pnlmodificar;
    private javax.swing.JPanel pnlremover;
    public static javax.swing.JTable tabla;
    public static javax.swing.JTextArea txtDescripcion;
    // End of variables declaration//GEN-END:variables
}
