/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package paneles.Ventas;

import A_alertas.principal.*;
import A_tabla.*;
import A_tabla.MyScrollbarUI;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.util.*;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import leer_numero.TareasProgramacion;
import paneles.Productos.Opciones;
import static paneles.Ventas.Ventas.*;
import static paneles.Z_Usuarios.Usuario.txtNombre;


/**
 *
 * @author jona
 */
public class Cobrar extends javax.swing.JDialog {
    int x, y;
    
    Timer timer = null;
    TimerTask task;
    int i = 32;
    TareasProgramacion NumLetra = new TareasProgramacion();

    /**
     * Creates new form Error
     *
     * @param parent
     * @param modal
     */
    public Cobrar(JFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        AWTUtilities.setOpaque(this, false);
        Ubicar(0);
        Double a=Double.parseDouble(Ventas.lblTotal.getText());
        total_cobrar.setText(""+ a);
        
        total_cobrar.setHorizontalAlignment(JLabel.CENTER);
        total_cobrar.setVerticalAlignment(JLabel.CENTER);
        TotalP.setHorizontalAlignment(JLabel.CENTER);
        TotalP.setVerticalAlignment(JLabel.CENTER);
        letra.setHorizontalAlignment(JLabel.CENTER);
        letra.setVerticalAlignment(JLabel.CENTER);
        letra1.setHorizontalAlignment(JLabel.CENTER);
        letra1.setVerticalAlignment(JLabel.CENTER);
        Cambio.setHorizontalAlignment(JLabel.CENTER);
        Cambio.setVerticalAlignment(JLabel.CENTER);
        total_cambio.setHorizontalAlignment(JLabel.CENTER);
        total_cambio.setVerticalAlignment(JLabel.CENTER);
        
        String s=Ventas.lblTotal.getText();
        letra.setText("("+NumLetra.Convertir(s)+")");
        paneles.Ventas.Opciones.calcularcambio();
        
        String aa=total_cambio.getText();
        letra1.setText("("+NumLetra.Convertir(aa)+")");
        efectivo.requestFocus();
      
    }
   
    
   
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        rSButtonMetro1 = new rsbuttom.RSButtonMetro();
        total_cobrar = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TotalP = new javax.swing.JLabel();
        letra = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        total_cambio = new javax.swing.JLabel();
        Cambio = new javax.swing.JLabel();
        letra1 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        efectivo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tarjeta = new javax.swing.JTextField();
        vales = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cheques = new javax.swing.JTextField();
        transfer = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        materialButton5 = new principal.MaterialButton();
        jLabel6 = new javax.swing.JLabel();
        lblefectivo = new javax.swing.JTextField();
        lbltarjeta = new javax.swing.JTextField();
        lblvales = new javax.swing.JTextField();
        lblcheques = new javax.swing.JTextField();
        lbltransfer = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cobrar = new principal.MaterialButton();
        materialButton7 = new principal.MaterialButton();

        setUndecorated(true);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(102, 102, 102)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(210, 210, 214));
        jPanel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel5MouseDragged(evt);
            }
        });
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonMetro1.setText("X");
        rSButtonMetro1.setColorHover(new java.awt.Color(102, 102, 102));
        rSButtonMetro1.setColorNormal(new java.awt.Color(210, 210, 214));
        rSButtonMetro1.setColorPressed(new java.awt.Color(136, 0, 0));
        rSButtonMetro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro1ActionPerformed(evt);
            }
        });
        jPanel5.add(rSButtonMetro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 30, 30));

        jPanel6.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 690, -1));

        total_cobrar.setFont(new java.awt.Font("Trebuchet MS", 1, 40)); // NOI18N
        total_cobrar.setForeground(new java.awt.Color(153, 0, 0));
        total_cobrar.setText("123456");
        jPanel6.add(total_cobrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 136, 380, 38));
        jPanel6.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 94, 380, -1));
        jPanel6.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 128, 380, -1));
        jPanel6.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 209, 380, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel1.setText("Ticket");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(305, 305, 305)
                .addComponent(jLabel1)
                .addContainerGap(281, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 38, 670, -1));

        TotalP.setFont(new java.awt.Font("Trebuchet MS", 0, 17)); // NOI18N
        TotalP.setForeground(new java.awt.Color(153, 0, 0));
        TotalP.setText("Total a Pagar");
        jPanel6.add(TotalP, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 102, 380, -1));

        letra.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        letra.setText("(Catorce Mil Setecientos Ochenta y Nueve 00/100 M.N.)");
        jPanel6.add(letra, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 185, 380, -1));
        jPanel6.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 332, 380, -1));

        total_cambio.setFont(new java.awt.Font("Trebuchet MS", 1, 40)); // NOI18N
        total_cambio.setForeground(new java.awt.Color(0, 153, 0));
        total_cambio.setText("123456");
        jPanel6.add(total_cambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 259, 380, 50));

        Cambio.setFont(new java.awt.Font("Trebuchet MS", 0, 17)); // NOI18N
        Cambio.setForeground(new java.awt.Color(0, 153, 0));
        Cambio.setText("Cambio");
        jPanel6.add(Cambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 225, 380, -1));

        letra1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        letra1.setText("(Catorce Mil Setecientos Ochenta y Nueve 00/100 M.N.)");
        jPanel6.add(letra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 308, 380, -1));
        jPanel6.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 217, 380, -1));
        jPanel6.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 251, 380, -1));
        jPanel6.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 340, 670, 10));
        jPanel6.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 86, 670, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("Efectivo:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 64, 24));

        efectivo.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        efectivo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                efectivoFocusLost(evt);
            }
        });
        efectivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                efectivoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                efectivoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                efectivoKeyTyped(evt);
            }
        });
        jPanel2.add(efectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 11, 120, -1));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setText("Cheques:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 64, 24));

        tarjeta.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel2.add(tarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 41, 120, -1));

        vales.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel2.add(vales, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 71, 120, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText("     Vales:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 71, 64, 24));

        cheques.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel2.add(cheques, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 101, 120, -1));

        transfer.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel2.add(transfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 131, 120, -1));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel7.setText("Transfer:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 131, 64, 24));

        materialButton5.setBackground(new java.awt.Color(204, 204, 204));
        materialButton5.setForeground(new java.awt.Color(102, 102, 102));
        materialButton5.setText("Asignar Credito");
        materialButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        materialButton5.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        materialButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialButton5ActionPerformed(evt);
            }
        });
        materialButton5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                materialButton5KeyTyped(evt);
            }
        });
        jPanel2.add(materialButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 161, 190, 34));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setText(" Tarjeta:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 64, 24));

        lblefectivo.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblefectivo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblefectivoFocusLost(evt);
            }
        });
        lblefectivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblefectivoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblefectivoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lblefectivoKeyTyped(evt);
            }
        });
        jPanel2.add(lblefectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 11, 70, -1));

        lbltarjeta.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lbltarjeta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lbltarjetaFocusLost(evt);
            }
        });
        lbltarjeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lbltarjetaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lbltarjetaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lbltarjetaKeyTyped(evt);
            }
        });
        jPanel2.add(lbltarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 41, 70, -1));

        lblvales.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblvales.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblvalesFocusLost(evt);
            }
        });
        lblvales.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblvalesKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblvalesKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lblvalesKeyTyped(evt);
            }
        });
        jPanel2.add(lblvales, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 71, 70, -1));

        lblcheques.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblcheques.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblchequesFocusLost(evt);
            }
        });
        lblcheques.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblchequesKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblchequesKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lblchequesKeyTyped(evt);
            }
        });
        jPanel2.add(lblcheques, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 101, 70, -1));

        lbltransfer.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lbltransfer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lbltransferFocusLost(evt);
            }
        });
        lbltransfer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lbltransferKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lbltransferKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lbltransferKeyTyped(evt);
            }
        });
        jPanel2.add(lbltransfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 131, 70, -1));

        jPanel6.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 128, 280, 206));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Imagenes/moneda_nac.PNG"))); // NOI18N
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 356, -1, -1));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel10.setText("Moneda Asignada:");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 356, -1, 26));

        cobrar.setBackground(new java.awt.Color(204, 204, 204));
        cobrar.setForeground(new java.awt.Color(102, 102, 102));
        cobrar.setText("Cobrar");
        cobrar.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        cobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobrarActionPerformed(evt);
            }
        });
        cobrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cobrarKeyTyped(evt);
            }
        });
        jPanel6.add(cobrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 207, 41));

        materialButton7.setBackground(new java.awt.Color(255, 255, 253));
        materialButton7.setForeground(new java.awt.Color(0, 0, 153));
        materialButton7.setMnemonic('A');
        materialButton7.setText("Opciones de Pago (Ctrl + A)");
        materialButton7.setBorderPainted(false);
        materialButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        materialButton7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        materialButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialButton7ActionPerformed(evt);
            }
        });
        materialButton7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                materialButton7KeyTyped(evt);
            }
        });
        jPanel6.add(materialButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 200, 34));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel5MousePressed

    private void jPanel5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseDragged
        Point mueve = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(mueve.x - x, mueve.y - y);
    }//GEN-LAST:event_jPanel5MouseDragged

    private void rSButtonMetro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_rSButtonMetro1ActionPerformed

    private void materialButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_materialButton5ActionPerformed

    private void materialButton5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_materialButton5KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_materialButton5KeyTyped

    private void cobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobrarActionPerformed
        if(lblefectivo.getText().equals(""))
        {
            WarningAlert er = new WarningAlert(new JFrame(), true);
                er.titulo.setText("Mensaje");
                er.msj.setText("No se ha registrado");
                er.msj1.setText("el metodo de pago");
                er.setVisible(true);
        }
        else
        {
                paneles.Ventas.Sentencias s = new Sentencias();
                int contador = 0;
                for (int i = 0; i < paneles.Ventas.Ventas.tablaVentas.getRowCount(); i++) 
                {
                        s.setId_venta(Integer.parseInt(paneles.Ventas.Ventas.numVenta.getText()));
                        s.setCodigo( paneles.Ventas.Ventas.tablaVentas.getValueAt(i, 0).toString());
                        s.setCantidad(Integer.parseInt(paneles.Ventas.Ventas.tablaVentas.getValueAt(i, 3).toString()));
                        s.setTotal(Double.parseDouble(paneles.Ventas.Ventas.tablaVentas.getValueAt(i, 4).toString()));
                        s.setFecha(paneles.Ventas.Ventas.txtFecha.getText());
                        int opcion = paneles.Ventas.Opciones.registrar(s);
                        if (opcion != 0) 
                        {
                            contador++;
                        }

                        if (contador == paneles.Ventas.Ventas.tablaVentas.getRowCount()) 
                        {
                            limpiaCampos();
                            SuccessAlert sa = new SuccessAlert(new JFrame(), true);
                            sa.titulo.setText("¡HECHO!");
                            sa.msj.setText("VENTA REALIZADA CON");
                            sa.msj1.setText("ÉXITO");
                            sa.setVisible(true);
                        }
                
            }
        
            
        }
        
        
    }//GEN-LAST:event_cobrarActionPerformed

    private void cobrarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cobrarKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_cobrarKeyTyped

    private void materialButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialButton7ActionPerformed
        new paneles.Ventas.InfoOpcionesPago(new JFrame(), true).setVisible(true);
    }//GEN-LAST:event_materialButton7ActionPerformed

    private void materialButton7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_materialButton7KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_materialButton7KeyTyped

    private void efectivoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_efectivoFocusLost
        if(efectivo.getText().equals("."))
        {
            efectivo.setText("");
        }
    }//GEN-LAST:event_efectivoFocusLost

    private void efectivoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_efectivoKeyTyped
        int limite =6;
        if (efectivo.getText().length()== limite)
        {
            evt.consume();
        }
        
        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.') 
        {
            evt.consume();
            
        }
        if (evt.getKeyChar() == '.' && efectivo.getText().contains(".")) 
        {
            evt.consume();
        }
        if (Character.isAlphabetic(evt.getKeyChar())) 
        {
            getToolkit().beep();
            evt.consume();
        }
      
        
    }//GEN-LAST:event_efectivoKeyTyped

    private void efectivoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_efectivoKeyReleased
        
    }//GEN-LAST:event_efectivoKeyReleased

    private void efectivoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_efectivoKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            if(efectivo.getText().equals("."))
            {
                efectivo.setText("");
            }
            else
            {
                String efect = this.efectivo.getText();
                String lblefect = this.lblefectivo.getText();
                System.out.println(""+lblefect);
                
                
                if(lblefect.equals(""))
                {
                    lblefect="0.0";
                    Double recibe= Double.parseDouble(efect);
                    Double hay= Double.parseDouble(lblefect);
                    Double total = 0.0;
                    total = hay+recibe;
                    ////
                    lblefectivo.setText(""+ total);
                    Cambio.setText("Cambio");
                    paneles.Ventas.Opciones.calcularcambio();
                    String a=total_cambio.getText();
                    letra1.setText("("+NumLetra.Convertir(a)+")");
                    efectivo.setText("");
                }
                else
                {
                    Double recibe= Double.parseDouble(efect);
                    Double hay= Double.parseDouble(lblefect);
                    Double total = 0.0;
                    total = hay+recibe;
                    lblefectivo.setText(""+ total);
                    Cambio.setText("Cambio");
                    paneles.Ventas.Opciones.calcularcambio();
                    String a=total_cambio.getText();
                    letra1.setText("("+NumLetra.Convertir(a)+")");
                    efectivo.setText("");
                }
                
                
            }
        }
    }//GEN-LAST:event_efectivoKeyPressed

    private void lblefectivoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblefectivoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_lblefectivoFocusLost

    private void lblefectivoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblefectivoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblefectivoKeyPressed

    private void lblefectivoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblefectivoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lblefectivoKeyReleased

    private void lblefectivoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblefectivoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_lblefectivoKeyTyped

    private void lbltarjetaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lbltarjetaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_lbltarjetaFocusLost

    private void lbltarjetaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbltarjetaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbltarjetaKeyPressed

    private void lbltarjetaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbltarjetaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lbltarjetaKeyReleased

    private void lbltarjetaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbltarjetaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_lbltarjetaKeyTyped

    private void lblvalesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblvalesFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_lblvalesFocusLost

    private void lblvalesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblvalesKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblvalesKeyPressed

    private void lblvalesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblvalesKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lblvalesKeyReleased

    private void lblvalesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblvalesKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_lblvalesKeyTyped

    private void lblchequesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblchequesFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_lblchequesFocusLost

    private void lblchequesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblchequesKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblchequesKeyPressed

    private void lblchequesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblchequesKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lblchequesKeyReleased

    private void lblchequesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblchequesKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_lblchequesKeyTyped

    private void lbltransferFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lbltransferFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_lbltransferFocusLost

    private void lbltransferKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbltransferKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbltransferKeyPressed

    private void lbltransferKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbltransferKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lbltransferKeyReleased

    private void lbltransferKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbltransferKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_lbltransferKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
             public void run() {
                Productos dialog = new Productos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Cambio;
    private javax.swing.JLabel TotalP;
    public static javax.swing.JTextField cheques;
    private principal.MaterialButton cobrar;
    public static javax.swing.JTextField efectivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    public static javax.swing.JTextField lblcheques;
    public static javax.swing.JTextField lblefectivo;
    public static javax.swing.JTextField lbltarjeta;
    public static javax.swing.JTextField lbltransfer;
    public static javax.swing.JTextField lblvales;
    private javax.swing.JLabel letra;
    private javax.swing.JLabel letra1;
    private principal.MaterialButton materialButton5;
    private principal.MaterialButton materialButton7;
    private rsbuttom.RSButtonMetro rSButtonMetro1;
    public static javax.swing.JTextField tarjeta;
    public static javax.swing.JLabel total_cambio;
    public static javax.swing.JLabel total_cobrar;
    public static javax.swing.JTextField transfer;
    public static javax.swing.JTextField vales;
    // End of variables declaration//GEN-END:variables
private void Cerrar() {
        this.dispose();
        timer = null;
        task = null;
    }

    private void Trasparencia(float trasp) {
        AWTUtilities.setOpacity(this, trasp);
    }

    private void Ubicar(int y) {
        setLocationRelativeTo(null);
    }
   
    void limpiaCampos() {
        DefaultTableModel modelo = (DefaultTableModel) tablaVentas.getModel();

        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
        lblTotal.setText("0.0");
        txtFecha.setText(fechaactual());
        paneles.Ventas.Opciones.numerosVenta();
        this.dispose();
    }
    
   
}
