/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package paneles.Ventas;

import A_alertas.principal.ErrorAlert;
import A_tabla.EstiloTablaHeader;
import A_tabla.EstiloTablaRenderer;
import A_tabla.MyScrollbarUI;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.ListSelectionModel;
import javax.swing.border.EtchedBorder;
import javax.swing.table.DefaultTableModel;
import static paneles.Ventas.Ventas.lblTotal;
import static paneles.Ventas.Ventas.tablaVentas;
import static paneles.Ventas.Ventas.txtFecha;
import static paneles.Z_Compras.pnlCompras.tabla;

/**
 *
 * @author jona
 */
public class Ventas extends javax.swing.JPanel {

    /**
     * Creates new form Ventt
     */
    public Ventas() {
        initComponents();
        this.tablaVentas.getTableHeader().setDefaultRenderer(new EstiloTablaHeader());
        this.tablaVentas.setDefaultRenderer(Object.class, new EstiloTablaRenderer());
        this.tablaVentas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.getViewport().setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.getViewport().setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.getVerticalScrollBar().setUI(new MyScrollbarUI());
        jScrollPane1.getHorizontalScrollBar().setUI(new MyScrollbarUI());
        paneles.Ventas.Opciones.numerosVenta();
        limpiaCampos();
        this.txtFecha.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVentas = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        pnlcotizacion = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        pnlarticulos = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        pnlok = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        busca_1 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pnlprecio = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pnlmovcaja = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pnlcantidad = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pnlremover = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        pnldescuento = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        pnlcheck = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        pnlbuscar = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFecha = new app.bolivia.swing.JCTextField();
        numVenta = new javax.swing.JLabel();
        numVenta1 = new javax.swing.JLabel();
        tipo = new componentes.org1.bolivia.combo.SComboBox();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Total: $");

        lblTotal.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(353, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
            .addComponent(lblTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Articulo", "Precio Venta", "Cantidad", "Importe"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(tablaVentas);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Imagenes/codigobarras.PNG"))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        pnlcotizacion.setBackground(new java.awt.Color(225, 225, 225));
        pnlcotizacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlcotizacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlcotizacionMouseExited(evt);
            }
        });
        pnlcotizacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Imagenes/coti.PNG"))); // NOI18N
        pnlcotizacion.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 35));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setText("   Cotizacion");
        pnlcotizacion.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 80, 20));

        pnlarticulos.setBackground(new java.awt.Color(225, 225, 225));
        pnlarticulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlarticulosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlarticulosMouseExited(evt);
            }
        });
        pnlarticulos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Imagenes/produ.PNG"))); // NOI18N
        pnlarticulos.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 35));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setText("    Articulos");
        pnlarticulos.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 80, 20));

        pnlok.setBackground(new java.awt.Color(225, 225, 225));
        pnlok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlokMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlokMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlokMouseExited(evt);
            }
        });
        pnlok.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Imagenes/ok.PNG"))); // NOI18N
        pnlok.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 0, 50, 35));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel32.setText("  Cobrar");
        pnlok.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 70, 20));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlcotizacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlok, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlarticulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(pnlcotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(pnlok, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 60, Short.MAX_VALUE)
                    .addComponent(pnlarticulos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 60, Short.MAX_VALUE)))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Imagenes/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 9, 110, 140));

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 0, 0), new java.awt.Color(153, 0, 0)));
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Imagenes/tipo vendedor.PNG"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Imagenes/tic.PNG"))); // NOI18N

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        busca_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Imagenes/lup.PNG"))); // NOI18N
        busca_1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(225, 225, 225), null));
        busca_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                busca_1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                busca_1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                busca_1MouseExited(evt);
            }
        });
        jPanel7.add(busca_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        jPanel12.setBackground(new java.awt.Color(204, 204, 204));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("    Ventas");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 60));

        jPanel12.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 60));

        pnlprecio.setBackground(new java.awt.Color(225, 225, 225));
        pnlprecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlprecioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlprecioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlprecioMouseExited(evt);
            }
        });
        pnlprecio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("     Precio");
        pnlprecio.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 80, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Imagenes/precioc.PNG"))); // NOI18N
        pnlprecio.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 40, 40));

        jPanel12.add(pnlprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, 60));

        pnlmovcaja.setBackground(new java.awt.Color(225, 225, 225));
        pnlmovcaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlmovcajaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlmovcajaMouseExited(evt);
            }
        });
        pnlmovcaja.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Imagenes/movcaja.PNG"))); // NOI18N
        pnlmovcaja.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 35));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("   Mov.Caja");
        pnlmovcaja.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 80, 20));

        jPanel12.add(pnlmovcaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, -1, 60));

        pnlcantidad.setBackground(new java.awt.Color(225, 225, 225));
        pnlcantidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlcantidadMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlcantidadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlcantidadMouseExited(evt);
            }
        });
        pnlcantidad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Imagenes/cant.PNG"))); // NOI18N
        pnlcantidad.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 40, 35));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("   Cantidad");
        pnlcantidad.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 80, 20));

        jPanel12.add(pnlcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, -1, 60));

        pnlremover.setBackground(new java.awt.Color(225, 225, 225));
        pnlremover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlremoverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlremoverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlremoverMouseExited(evt);
            }
        });
        pnlremover.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Imagenes/menos.PNG"))); // NOI18N
        pnlremover.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 60, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("   Remover");
        pnlremover.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 80, 20));

        jPanel12.add(pnlremover, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 80, 60));

        pnldescuento.setBackground(new java.awt.Color(225, 225, 225));
        pnldescuento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnldescuentoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnldescuentoMouseExited(evt);
            }
        });
        pnldescuento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("      Desc.");
        pnldescuento.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 80, 20));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Imagenes/porciento.PNG"))); // NOI18N
        pnldescuento.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 30, 30));

        jPanel12.add(pnldescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, -1, 60));

        pnlcheck.setBackground(new java.awt.Color(225, 225, 225));
        pnlcheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlcheckMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlcheckMouseExited(evt);
            }
        });
        pnlcheck.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Imagenes/chec.PNG"))); // NOI18N
        pnlcheck.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 30, 30));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setText("     check");
        pnlcheck.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 80, 20));

        jPanel12.add(pnlcheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, -1, 60));

        pnlbuscar.setBackground(new java.awt.Color(225, 225, 225));
        pnlbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlbuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlbuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlbuscarMouseExited(evt);
            }
        });
        pnlbuscar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("     Buscar");
        pnlbuscar.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 80, 20));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Imagenes/lupa_buscar.png"))); // NOI18N
        pnlbuscar.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 70, 35));

        jPanel12.add(pnlbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Subtotal: $");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Descuento: $");

        txtFecha.setBorder(null);
        txtFecha.setForeground(new java.awt.Color(58, 159, 171));
        txtFecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtFecha.setPlaceholder("FECHA");

        numVenta.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        numVenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numVenta.setText("NO. VENTA");

        numVenta1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        numVenta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numVenta1.setText("No.Venta:");

        tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ticket", "Nota", "Factura" }));
        tipo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(120, 120, 120))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(numVenta1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numVenta)
                        .addGap(108, 108, 108)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(358, 358, 358)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(numVenta1)
                                    .addComponent(numVenta)
                                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(9, 9, 9)
                                .addComponent(jLabel5))
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pnlcotizacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlcotizacionMouseEntered
        pnlcotizacion.setBorder(new EtchedBorder(EtchedBorder.RAISED,Color.gray,Color.LIGHT_GRAY));
    }//GEN-LAST:event_pnlcotizacionMouseEntered

    private void pnlcotizacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlcotizacionMouseExited
        pnlcotizacion.setBorder(new EtchedBorder(EtchedBorder.RAISED,new java.awt.Color(225,225,225),new java.awt.Color(225,225,225)));
    }//GEN-LAST:event_pnlcotizacionMouseExited

    private void pnlarticulosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlarticulosMouseEntered
        pnlarticulos.setBorder(new EtchedBorder(EtchedBorder.RAISED,Color.gray,Color.LIGHT_GRAY));
    }//GEN-LAST:event_pnlarticulosMouseEntered

    private void pnlarticulosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlarticulosMouseExited
        pnlarticulos.setBorder(new EtchedBorder(EtchedBorder.RAISED,new java.awt.Color(225,225,225),new java.awt.Color(225,225,225)));
    }//GEN-LAST:event_pnlarticulosMouseExited

    private void pnlokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlokMouseClicked
        if (this.tablaVentas.getRowCount() < 1)
        {
            ErrorAlert er = new ErrorAlert(new JFrame(), true);
            er.titulo.setText("Mensaje");
            er.msj.setText("No se han añadido articulos");
            er.msj1.setText("a la venta");
            er.setVisible(true);
        } else {
            new paneles.Ventas.Cobrar(new JFrame(), true).setVisible(true);

        }
    }//GEN-LAST:event_pnlokMouseClicked

    private void pnlokMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlokMouseEntered
        pnlok.setBorder(new EtchedBorder(EtchedBorder.RAISED,Color.gray,Color.LIGHT_GRAY));
    }//GEN-LAST:event_pnlokMouseEntered

    private void pnlokMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlokMouseExited
        pnlok.setBorder(new EtchedBorder(EtchedBorder.RAISED,new java.awt.Color(225,225,225),new java.awt.Color(225,225,225)));
    }//GEN-LAST:event_pnlokMouseExited

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed

        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if (tabla.getRowCount() > 0) {
                try {
                    String cant = null;
                    DefaultTableModel tabladet = (DefaultTableModel) paneles.Ventas.Ventas.tablaVentas.getModel();

                    String[] dato = new String[5];

                    int fila = tabla.getSelectedRow();

                    String cod = tabla.getValueAt(fila, 0).toString();
                    String nom = tabla.getValueAt(fila, 1).toString();
                    String precio = tabla.getValueAt(fila, 2).toString();
                    int c = 0;
                    int j = 0;
                    cant = "1";
                    if ((cant.equals("")) || (cant.equals("0"))) {

                    } else {
                        for (int i = 0; i < paneles.Ventas.Ventas.tablaVentas.getRowCount(); i++) {
                            Object com = paneles.Ventas.Ventas.tablaVentas.getValueAt(i, 0);
                            Object cant1 = paneles.Ventas.Ventas.tablaVentas.getValueAt(i, 3);
                            if (cod.equals(com)) {
                                j = i;
                                int cantT = Integer.parseInt(cant) + Integer.parseInt((String) cant1);
                                paneles.Ventas.Ventas.tablaVentas.setValueAt(String.valueOf(cantT), i, 3);
                                c++;
                                paneles.Ventas.Opciones.calcular();
                            }
                        }
                        if (c == 0) {

                            dato[0] = cod;
                            dato[1] = nom;
                            dato[2] = precio;
                            dato[3] = cant;

                            tabladet.addRow(dato);
                            paneles.Ventas.Opciones.calcular();

                        }
                    }
                } catch (Exception e) {

                }
            } else {
                ErrorAlert er = new ErrorAlert(new JFrame(), true);
                er.titulo.setText("Mensaje");
                er.msj.setText("No se han encontrado");
                er.msj1.setText("Registros");
                er.setVisible(true);
            }
        }

        /*if(evt.getKeyCode()==KeyEvent.VK_ESCAPE){
            System.exit(0);
        }*/

    }//GEN-LAST:event_jTextField2KeyPressed

    private void busca_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busca_1MouseClicked
        new paneles.Ventas.Productos(new JFrame(), true).setVisible(true);
    }//GEN-LAST:event_busca_1MouseClicked

    private void busca_1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busca_1MouseEntered
        busca_1.setBorder(new EtchedBorder(EtchedBorder.RAISED,Color.gray,Color.LIGHT_GRAY));
    }//GEN-LAST:event_busca_1MouseEntered

    private void busca_1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busca_1MouseExited
        busca_1.setBorder(new EtchedBorder(EtchedBorder.RAISED,new java.awt.Color(225,225,225),new java.awt.Color(225,225,225)));
    }//GEN-LAST:event_busca_1MouseExited

    private void pnlprecioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlprecioMouseClicked

    }//GEN-LAST:event_pnlprecioMouseClicked

    private void pnlprecioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlprecioMouseEntered
        pnlprecio.setBorder(new EtchedBorder(EtchedBorder.RAISED,Color.gray,Color.LIGHT_GRAY));
    }//GEN-LAST:event_pnlprecioMouseEntered

    private void pnlprecioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlprecioMouseExited
        pnlprecio.setBorder(new EtchedBorder(EtchedBorder.RAISED,new java.awt.Color(225,225,225),new java.awt.Color(225,225,225)));
    }//GEN-LAST:event_pnlprecioMouseExited

    private void pnlmovcajaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlmovcajaMouseEntered
        pnlmovcaja.setBorder(new EtchedBorder(EtchedBorder.RAISED,Color.gray,Color.LIGHT_GRAY));
    }//GEN-LAST:event_pnlmovcajaMouseEntered

    private void pnlmovcajaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlmovcajaMouseExited
        pnlmovcaja.setBorder(new EtchedBorder(EtchedBorder.RAISED,new java.awt.Color(225,225,225),new java.awt.Color(225,225,225)));
    }//GEN-LAST:event_pnlmovcajaMouseExited

    private void pnlcantidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlcantidadMouseClicked
        if (this.tablaVentas.getRowCount() < 1) {
            ErrorAlert er = new ErrorAlert(new JFrame(), true);
            er.titulo.setText("Mensaje");
            er.msj.setText("No hay productos");
            er.msj1.setText("agregados a la venta");
            er.setVisible(true);
        } else {
            if (this.tablaVentas.getSelectedRowCount() < 1) {
                ErrorAlert er = new ErrorAlert(new JFrame(), true);
                er.titulo.setText("Mensaje");
                er.msj.setText("Seleccione almenos un");
                er.msj1.setText("registro");
                er.setVisible(true);
            } else {
                new paneles.Ventas.opcionesventas.Cantidad_P(new JFrame(), true).setVisible(true);
            }
        }
    }//GEN-LAST:event_pnlcantidadMouseClicked

    private void pnlcantidadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlcantidadMouseEntered
        pnlcantidad.setBorder(new EtchedBorder(EtchedBorder.RAISED,Color.gray,Color.LIGHT_GRAY));
    }//GEN-LAST:event_pnlcantidadMouseEntered

    private void pnlcantidadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlcantidadMouseExited
        pnlcantidad.setBorder(new EtchedBorder(EtchedBorder.RAISED,new java.awt.Color(225,225,225),new java.awt.Color(225,225,225)));
    }//GEN-LAST:event_pnlcantidadMouseExited

    private void pnlremoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlremoverMouseClicked
        if (tablaVentas.getRowCount() > 0) {
            DefaultTableModel modelo = (DefaultTableModel) tablaVentas.getModel();
            int fila = tablaVentas.getSelectedRow();
            if (fila >= 0) {
                modelo.removeRow(fila);
                Opciones.calcular();
            } else {
                ErrorAlert er = new ErrorAlert(new JFrame(), true);
                er.titulo.setText("Mensaje");
                er.msj.setText("Seleccione almenos un");
                er.msj1.setText("producto agregado");
                er.setVisible(true);
            }
        } else {
            ErrorAlert er = new ErrorAlert(new JFrame(), true);
            er.titulo.setText("Mensaje");
            er.msj.setText("No hay registros");
            er.msj1.setText("para eliminar");
            er.setVisible(true);
        }
    }//GEN-LAST:event_pnlremoverMouseClicked

    private void pnlremoverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlremoverMouseEntered
        pnlremover.setBorder(new EtchedBorder(EtchedBorder.RAISED,Color.gray,Color.LIGHT_GRAY));
    }//GEN-LAST:event_pnlremoverMouseEntered

    private void pnlremoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlremoverMouseExited
        pnlremover.setBorder(new EtchedBorder(EtchedBorder.RAISED,new java.awt.Color(225,225,225),new java.awt.Color(225,225,225)));
    }//GEN-LAST:event_pnlremoverMouseExited

    private void pnldescuentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnldescuentoMouseEntered
        pnldescuento.setBorder(new EtchedBorder(EtchedBorder.RAISED,Color.gray,Color.LIGHT_GRAY));
    }//GEN-LAST:event_pnldescuentoMouseEntered

    private void pnldescuentoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnldescuentoMouseExited
        pnldescuento.setBorder(new EtchedBorder(EtchedBorder.RAISED,new java.awt.Color(225,225,225),new java.awt.Color(225,225,225)));
    }//GEN-LAST:event_pnldescuentoMouseExited

    private void pnlcheckMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlcheckMouseEntered
        pnlcheck.setBorder(new EtchedBorder(EtchedBorder.RAISED,Color.gray,Color.LIGHT_GRAY));
    }//GEN-LAST:event_pnlcheckMouseEntered

    private void pnlcheckMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlcheckMouseExited
        pnlcheck.setBorder(new EtchedBorder(EtchedBorder.RAISED,new java.awt.Color(225,225,225),new java.awt.Color(225,225,225)));
    }//GEN-LAST:event_pnlcheckMouseExited

    private void pnlbuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlbuscarMouseClicked
        new paneles.Ventas.Productos(new JFrame(), true).setVisible(true);
    }//GEN-LAST:event_pnlbuscarMouseClicked

    private void pnlbuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlbuscarMouseEntered
        pnlbuscar.setBorder(new EtchedBorder(EtchedBorder.RAISED,Color.gray,Color.LIGHT_GRAY));
    }//GEN-LAST:event_pnlbuscarMouseEntered

    private void pnlbuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlbuscarMouseExited
        pnlbuscar.setBorder(new EtchedBorder(EtchedBorder.RAISED,new java.awt.Color(225,225,225),new java.awt.Color(225,225,225)));
    }//GEN-LAST:event_pnlbuscarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel busca_1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField2;
    public static javax.swing.JLabel lblTotal;
    public static javax.swing.JLabel numVenta;
    public static javax.swing.JLabel numVenta1;
    private javax.swing.JPanel pnlarticulos;
    private javax.swing.JPanel pnlbuscar;
    private javax.swing.JPanel pnlcantidad;
    private javax.swing.JPanel pnlcheck;
    private javax.swing.JPanel pnlcotizacion;
    private javax.swing.JPanel pnldescuento;
    private javax.swing.JPanel pnlmovcaja;
    private javax.swing.JPanel pnlok;
    private javax.swing.JPanel pnlprecio;
    private javax.swing.JPanel pnlremover;
    public static javax.swing.JTable tablaVentas;
    public static componentes.org1.bolivia.combo.SComboBox tipo;
    public static app.bolivia.swing.JCTextField txtFecha;
    // End of variables declaration//GEN-END:variables
public static String fechaactual() {
        Date fecha = new Date();
        SimpleDateFormat formatofecha = new SimpleDateFormat("dd/MM/YYYY");
        return formatofecha.format(fecha);
    }

void limpiaCampos() {
        DefaultTableModel modelo = (DefaultTableModel) tablaVentas.getModel();

        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
        lblTotal.setText("0.0");
        txtFecha.setText(fechaactual());
        paneles.Ventas.Opciones.numerosVenta();
        
    }
}
