/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package paneles.Z_Usuarios;

import A_alertas.principal.*;
import java.awt.Cursor;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JFrame;
import static paneles.Proveedores.Proveedor.txtDireccion;
import static paneles.Proveedores.Proveedor.txtNumero;

/**
 *
 * @author jona
 */
public class Usuario extends javax.swing.JDialog {
    int x, y;
    
    Timer timer = null;
    TimerTask task;
    int i = 32;
    
    public Usuario(JFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        AWTUtilities.setOpaque(this, false);
        this.id.setVisible(false);
        this.nombreUs.setVisible(false);
        this.tipo.setCursor(new Cursor(12));
        this.txtNombre.requestFocus();
        Ubicar(0);
    }
    
     private void limpiarCampos() {
        this.txtNombre.requestFocus();
        this.txtNombre.setText("");
        this.txtApellido_P.setText("");
        this.txtApellido_M.setText("");
        this.txtDireccion.setText("");
        this.txtNumero.setText("");
        this.txtUsuario.setText("");
        this.txtPassword.setText("");
        this.tipo.setSelectedIndex(0);
        Opciones.listar("");
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtApellido_M = new app.bolivia.swing.JCTextField();
        tipo = new componentes.org1.bolivia.combo.SComboBox();
        txtUsuario = new app.bolivia.swing.JCTextField();
        txtNombre = new app.bolivia.swing.JCTextField();
        txtApellido_P = new app.bolivia.swing.JCTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDireccion = new app.bolivia.swing.JCTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNumero = new app.bolivia.swing.JCTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtPassword = new jpass.JRPasswordField();
        jLabel17 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        rSButtonMetro1 = new rsbuttom.RSButtonMetro();
        id = new javax.swing.JLabel();
        nombreUs = new javax.swing.JLabel();
        limpiar = new principal.MaterialButton();
        registrar = new principal.MaterialButton();

        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(102, 102, 102)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Imagenes/usuarios.png"))); // NOI18N
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, -1, -1));

        titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titulo.setText("Usuarios");
        jPanel3.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 13, 330, 34));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtApellido_M.setBorder(null);
        txtApellido_M.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtApellido_M.setPlaceholder("Ej. Salgado");
        txtApellido_M.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellido_MKeyTyped(evt);
            }
        });
        jPanel2.add(txtApellido_M, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 220, 30));

        tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TIPO USUARIO", "ADMINISTRADOR", "NORMAL" }));
        tipo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 220, 30));

        txtUsuario.setBorder(null);
        txtUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUsuario.setPlaceholder("Ej. JuanMS");
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyTyped(evt);
            }
        });
        jPanel2.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 220, 30));

        txtNombre.setBorder(null);
        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNombre.setPlaceholder("Ej. Juan");
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 220, 30));

        txtApellido_P.setBorder(null);
        txtApellido_P.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtApellido_P.setPlaceholder("Ej. Martinez");
        txtApellido_P.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellido_PKeyTyped(evt);
            }
        });
        jPanel2.add(txtApellido_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 210, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Imagenes/linea_roja.PNG"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 220, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("           Primer Apellido:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 140, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Imagenes/linea_roja.PNG"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 220, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Imagenes/linea_roja.PNG"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 220, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Segundo Apellido:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 120, -1));

        txtDireccion.setBorder(null);
        txtDireccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDireccion.setPlaceholder("Ej. Valle de Bravo, Col. San Juan, No.2, Int: 2.");
        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionKeyTyped(evt);
            }
        });
        jPanel2.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 290, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Imagenes/linea_roja.PNG"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 220, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Dirección:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 70, -1));

        txtNumero.setBorder(null);
        txtNumero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNumero.setPlaceholder("Ej. 7224328907");
        txtNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroKeyTyped(evt);
            }
        });
        jPanel2.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 220, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Imagenes/linea_roja.PNG"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 220, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Número Telefonico:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 130, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 380, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Nombre del Empleado:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 20, 140, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Imagenes/linea_roja.PNG"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 220, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("                 Usuario:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 130, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Imagenes/linea_roja.PNG"))); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 220, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("   Rol del Empleado:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 317, 130, 30));

        txtPassword.setBorder(null);
        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPassword.setPlaceholder("********");
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPasswordKeyTyped(evt);
            }
        });
        jPanel2.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 220, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("           Contraseña:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 130, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Imagenes/linea_roja.PNG"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 220, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel6.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 32, -1, -1));

        jPanel5.setBackground(new java.awt.Color(210, 210, 214));
        jPanel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel5MouseDragged(evt);
            }
        });
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonMetro1.setText("X");
        rSButtonMetro1.setColorHover(new java.awt.Color(102, 102, 102));
        rSButtonMetro1.setColorNormal(new java.awt.Color(210, 210, 214));
        rSButtonMetro1.setColorPressed(new java.awt.Color(136, 0, 0));
        rSButtonMetro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro1ActionPerformed(evt);
            }
        });
        jPanel5.add(rSButtonMetro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 30, 30));

        id.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        id.setForeground(new java.awt.Color(51, 51, 51));
        id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        id.setText("id");
        jPanel5.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, 30, -1));

        nombreUs.setText("nombreUs");
        jPanel5.add(nombreUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 350, -1));

        jPanel6.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 430, -1));

        limpiar.setBackground(new java.awt.Color(204, 204, 204));
        limpiar.setForeground(new java.awt.Color(255, 255, 255));
        limpiar.setText("LIMPIAR CAMPOS");
        limpiar.setToolTipText("<html> <head> <style> #contenedor{background:#3A9FAB;color:white; padding-left:10px;padding-right:10px;margin:0; padding-top:5px;padding-bottom:5px;} </style> </head> <body> <h4 id=\"contenedor\">Limpiar campos</h4> </body> </html>");
        limpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        limpiar.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        jPanel6.add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 487, 160, 50));

        registrar.setBackground(new java.awt.Color(204, 204, 204));
        registrar.setForeground(new java.awt.Color(255, 255, 255));
        registrar.setText("REGISTRAR");
        registrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrar.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });
        registrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                registrarKeyTyped(evt);
            }
        });
        jPanel6.add(registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 487, 170, 50));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonMetro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_rSButtonMetro1ActionPerformed

    private void jPanel5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseDragged
        Point mueve = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(mueve.x - x, mueve.y - y);
    }//GEN-LAST:event_jPanel5MouseDragged

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel5MousePressed

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
        if (this.txtNombre.getText().equals("") || this.txtApellido_P.getText().equals("") || this.txtApellido_M.getText().equals("") || this.txtDireccion.getText().equals("") || this.txtNumero.getText().equals("") || this.txtPassword.getText().equals("")
            || this.tipo.getSelectedIndex() == 0) 
        {
            ErrorAlert er = new ErrorAlert(new JFrame(), true);
            er.titulo.setText("Mensaje");
            er.msj.setText("Hay campos vacios");
            er.msj1.setText("Favor de llenarlos");
            er.setVisible(true);

        } else {
            if (this.txtPassword.getText().length() <= 7) {
                ErrorAlert er = new ErrorAlert(new JFrame(), true);
                er.titulo.setText("mensaje");
                er.msj.setText("La contraseña debe tener");
                er.msj1.setText("minimo 8 caracteres");
                er.setVisible(true);
            } else {

                if (this.registrar.getText().equals("Guardar")) {

                    if (Opciones.verificaUsuario(this.txtUsuario.getText())
                        && !this.txtUsuario.getText().equals(this.nombreUs.getText())) {
                        ErrorAlert er = new ErrorAlert(new JFrame(), true);
                        er.titulo.setText("Mensaje");
                        er.msj.setText("El nombre de usuario");
                        er.msj1.setText("Ya éxiste");
                        er.setVisible(true);
                    } else {
                        Sentencias s = new Sentencias();
                        
                        s.setNombre(this.txtNombre.getText());
                        s.setApellido_P(this.txtApellido_P.getText());
                        s.setApellido_M(this.txtApellido_M.getText());
                        s.setDireccion(this.txtDireccion.getText());
                        s.setNumero(this.txtNumero.getText());
                        s.setUsuario(this.txtUsuario.getText());
                        s.setPassword(this.txtPassword.getText());
                        s.setTipo(this.tipo.getSelectedItem().toString());
                        s.setId(Integer.parseInt(this.id.getText()));

                        int opcion = Opciones.actualizar(s);
                        if (opcion != 0) {
                            Opciones.listar("");
                            SuccessAlert sa = new SuccessAlert(new JFrame(), true);
                            sa.titulo.setText("Mensaje");
                            sa.msj.setText("Se han guardado los campos");
                            sa.msj1.setText("exitosamente");
                            sa.setVisible(true);
                        }
                    }
                } else {
                    if (Opciones.verificaUsuario(this.txtUsuario.getText())) {
                        ErrorAlert er = new ErrorAlert(new JFrame(), true);
                        er.titulo.setText("Mensaje");
                        er.msj.setText("El nombre de usuario");
                        er.msj1.setText("Ya éxiste");
                        er.setVisible(true);
                    } else {
                        Sentencias s = new Sentencias();

                        s.setNombre(this.txtNombre.getText());
                        s.setApellido_P(this.txtApellido_P.getText());
                        s.setApellido_M(this.txtApellido_M.getText());
                        s.setDireccion(this.txtDireccion.getText());
                        s.setNumero(this.txtNumero.getText());
                        s.setUsuario(this.txtUsuario.getText());
                        s.setPassword(this.txtPassword.getText());
                        s.setTipo(this.tipo.getSelectedItem().toString());

                        int opcion = Opciones.registrar(s);
                        if (opcion != 0) {
                            limpiarCampos();
                            SuccessAlert sa = new SuccessAlert(new JFrame(), true);
                            sa.titulo.setText("Mensaje");
                            sa.msj.setText("Se ha registrado un");
                            sa.msj1.setText("Nuevo usuario");
                            sa.setVisible(true);
                            this.dispose();
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_registrarActionPerformed

    private void registrarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_registrarKeyTyped
        if ((evt.getKeyChar() == KeyEvent.VK_ENTER)) {
             if (this.txtNombre.getText().equals("") || this.txtApellido_P.getText().equals("") || this.txtApellido_M.getText().equals("") || this.txtNombre.getText().equals("") || this.txtDireccion.getText().equals("") || this.txtNumero.getText().equals("")
            || this.tipo.getSelectedIndex() == 0) {

            ErrorAlert er = new ErrorAlert(new JFrame(), true);
            er.titulo.setText("Mensaje");
            er.msj.setText("Hay campos vacios");
            er.msj1.setText("Favor de llenarlos");
            er.setVisible(true);

        } else {
            if (this.txtPassword.getText().length() <= 7) {
                ErrorAlert er = new ErrorAlert(new JFrame(), true);
                er.titulo.setText("mensaje");
                er.msj.setText("La contraseña debe tener");
                er.msj1.setText("minimo 8 caracteres");
                er.setVisible(true);
            } else {

                if (this.registrar.getText().equals("Guardar")) {

                    if (Opciones.verificaUsuario(this.txtUsuario.getText())
                        && !this.txtUsuario.getText().equals(this.nombreUs.getText())) {
                        ErrorAlert er = new ErrorAlert(new JFrame(), true);
                        er.titulo.setText("Mensaje");
                        er.msj.setText("El nombre de usuario");
                        er.msj1.setText("Ya éxiste");
                        er.setVisible(true);
                    } else {
                        Sentencias s = new Sentencias();
                        
                        s.setNombre(this.txtNombre.getText());
                        s.setApellido_P(this.txtApellido_P.getText());
                        s.setApellido_M(this.txtApellido_M.getText());
                        s.setDireccion(this.txtDireccion.getText());
                        s.setNumero(this.txtNumero.getText());
                        s.setUsuario(this.txtUsuario.getText());
                        s.setPassword(this.txtPassword.getText());
                        s.setTipo(this.tipo.getSelectedItem().toString());
                        s.setId(Integer.parseInt(this.id.getText()));

                        int opcion = Opciones.actualizar(s);
                        if (opcion != 0) {
                            Opciones.listar("");
                            SuccessAlert sa = new SuccessAlert(new JFrame(), true);
                            sa.titulo.setText("Mensaje");
                            sa.msj.setText("Se han guardado los campos");
                            sa.msj1.setText("exitosamente");
                            sa.setVisible(true);
                        }
                    }
                } else {
                    if (Opciones.verificaUsuario(this.txtUsuario.getText())) {
                        ErrorAlert er = new ErrorAlert(new JFrame(), true);
                        er.titulo.setText("Mensaje");
                        er.msj.setText("El nombre de usuario");
                        er.msj1.setText("Ya éxiste");
                        er.setVisible(true);
                    } else {
                        Sentencias s = new Sentencias();

                        s.setNombre(this.txtNombre.getText());
                        s.setApellido_P(this.txtApellido_P.getText());
                        s.setApellido_M(this.txtApellido_M.getText());
                        s.setDireccion(this.txtDireccion.getText());
                        s.setNumero(this.txtNumero.getText());
                        s.setUsuario(this.txtUsuario.getText());
                        s.setPassword(this.txtPassword.getText());
                        s.setTipo(this.tipo.getSelectedItem().toString());

                        int opcion = Opciones.registrar(s);
                        if (opcion != 0) {
                            limpiarCampos();
                            SuccessAlert sa = new SuccessAlert(new JFrame(), true);
                            sa.titulo.setText("Mensaje");
                            sa.msj.setText("Se ha registrado un");
                            sa.msj1.setText("Nuevo usuario");
                            sa.setVisible(true);
                        }
                    }
                }
            }
        }
        }
    }//GEN-LAST:event_registrarKeyTyped

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_limpiarActionPerformed

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreKeyPressed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
          char c=evt.getKeyChar(); 
          if(Character.isDigit(c)) { 
              getToolkit().beep(); 
              evt.consume(); 
          }
        
        int limite =20;
        if (txtNombre.getText().length()== limite)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellido_PKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellido_PKeyTyped
          char c=evt.getKeyChar(); 
          if(Character.isDigit(c)) { 
              getToolkit().beep(); 
              evt.consume(); 
          }
        int limite =20;
        if (txtApellido_P.getText().length()== limite)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtApellido_PKeyTyped

    private void txtApellido_MKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellido_MKeyTyped
        char c=evt.getKeyChar(); 
          if(Character.isDigit(c)) { 
              getToolkit().beep(); 
              evt.consume(); 
          }
        int limite =20;
        if (txtApellido_M.getText().length()== limite)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtApellido_MKeyTyped

    private void txtNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) ||
        (c == KeyEvent.VK_BACK_SPACE) ||
        (c == KeyEvent.VK_DELETE))) 
        {
            getToolkit().beep();
            evt.consume();
        }
        
        int limite =10;
        if (txtNumero.getText().length()== limite)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtNumeroKeyTyped

    private void txtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyTyped
        int limite =45;
        if (txtDireccion.getText().length()== limite)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtDireccionKeyTyped

    private void txtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyTyped
        char c=evt.getKeyChar(); 
          if(Character.isDigit(c)) { 
              getToolkit().beep(); 
              evt.consume(); 
          }
        int limite =10;
        if (txtUsuario.getText().length()== limite)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtUsuarioKeyTyped

    private void txtPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyTyped
        int limite =20;
        if (txtPassword.getText().length()== limite)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtPasswordKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
              public void run() {
                paneles.Z_Usuarios.Usuario dialog = new paneles.Z_Usuarios.Usuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel id;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private principal.MaterialButton limpiar;
    public static javax.swing.JLabel nombreUs;
    private rsbuttom.RSButtonMetro rSButtonMetro1;
    public static principal.MaterialButton registrar;
    public static componentes.org1.bolivia.combo.SComboBox tipo;
    public static javax.swing.JLabel titulo;
    public static app.bolivia.swing.JCTextField txtApellido_M;
    public static app.bolivia.swing.JCTextField txtApellido_P;
    public static app.bolivia.swing.JCTextField txtDireccion;
    public static app.bolivia.swing.JCTextField txtNombre;
    public static app.bolivia.swing.JCTextField txtNumero;
    public static jpass.JRPasswordField txtPassword;
    public static app.bolivia.swing.JCTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
    
    private void Cerrar() {
        this.dispose();
        timer = null;
        task = null;
    }
    private void Trasparencia(float trasp) {
        AWTUtilities.setOpacity(this, trasp);
    }
    private void Ubicar(int y) {
        this.setLocationRelativeTo(null);
    }
}
