

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package paneles;

import A_alertas.principal.ErrorAlert;
import A_alertas.principal.SuccessAlert;
import A_alertas.principal.WarningBackup;
import A_alertas.principal.WarningRestore;
import RespaldoBD.BackupMySQL;
import RespaldoBD.CargandoRestore;
import Template.Principal_Norm;
import java.awt.BorderLayout;
import java.awt.Color;
import java.io.File;
import javafx.stage.FileChooser;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.border.EtchedBorder;
import javax.swing.filechooser.FileNameExtensionFilter;
import paneles.Barras.pnlBarras;
import paneles.Productos.pnlProducto;
import paneles.Proveedores.pnlProveedor;
import paneles.Ventas.Ventas;
import paneles.Z_Acercade.pnlAbout;
import paneles.Z_Compras.pnlCompras;

/**
 *
 * @author jona
 */
public class pnlProcesos extends javax.swing.JPanel {

    /**
     * Creates new form pnlPrincipal
     */
    public pnlProcesos() {
        initComponents();
    }
    
    
    
    public static File existe = null;

    private void RestoreBackup() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new java.io.File("Respaldos/"));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos SQL (*.sql)", "sql");
        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.setFileFilter(filter);
        fileChooser.setDialogTitle("SELECCIONAR RESPALDO");
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            existe = fileChooser.getSelectedFile();
            if (existe.exists()) {

                WarningRestore a = new WarningRestore();
                a.msj1.setText("Has seleccionado un respaldo y la aplicación");
                a.msj2.setText("se reiniciara al terminar de restaurar la");
                a.msj3.setText("Base de Datos. Se recomienda que haga");
                a.msj4.setText("un respaldo antes de continuar.");
                a.lblTipo.setText("Restaurar");
                a.lblTipo.setVisible(false);
                a.setVisible(true);

                if (a.continuar) {
                    CargandoRestore a = new CargandoRestore();
                    a.setVisible(true);
                    a.dispose();
                    new splash.SplashScreen().setVisible(true);
                }

            } else {
                ErrorAlert a = new ErrorAlert(this, true);
                a.msj.setText("Archivo no encontrado.");
                a.msj1.setText("");
                a.setVisible(true);
            }
        }
        new ConexionBD().conexion();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        pnlOperaciones = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        panelgenerar = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        panelfactura = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelarticulos = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        panelcompras = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));

        pnlOperaciones.setBackground(new java.awt.Color(255, 255, 255));
        pnlOperaciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Imagenes/linea.png"))); // NOI18N
        pnlOperaciones.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 88, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Imagenes/linea.png"))); // NOI18N
        pnlOperaciones.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 460, -1, -1));

        panelgenerar.setBackground(new java.awt.Color(255, 255, 255));
        panelgenerar.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        panelgenerar.setForeground(new java.awt.Color(204, 0, 0));
        panelgenerar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelgenerarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelgenerarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelgenerarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelgenerarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelgenerarMouseReleased(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("    Generar");

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Imagenes/codigobarr.PNG"))); // NOI18N

        javax.swing.GroupLayout panelgenerarLayout = new javax.swing.GroupLayout(panelgenerar);
        panelgenerar.setLayout(panelgenerarLayout);
        panelgenerarLayout.setHorizontalGroup(
            panelgenerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelgenerarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelgenerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addGroup(panelgenerarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel20)))
                .addContainerGap())
        );
        panelgenerarLayout.setVerticalGroup(
            panelgenerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelgenerarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addGap(5, 5, 5))
        );

        pnlOperaciones.add(panelgenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 118, -1, -1));

        panelfactura.setBackground(new java.awt.Color(255, 255, 255));
        panelfactura.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        panelfactura.setForeground(new java.awt.Color(204, 0, 0));
        panelfactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelfacturaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelfacturaMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelfacturaMouseReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Exportar");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Imagenes/exportar excel .PNG"))); // NOI18N

        javax.swing.GroupLayout panelfacturaLayout = new javax.swing.GroupLayout(panelfactura);
        panelfactura.setLayout(panelfacturaLayout);
        panelfacturaLayout.setHorizontalGroup(
            panelfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelfacturaLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(panelfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3))
                .addGap(24, 24, 24))
        );
        panelfacturaLayout.setVerticalGroup(
            panelfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelfacturaLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(6, 6, 6))
        );

        pnlOperaciones.add(panelfactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 120, -1, -1));

        panelarticulos.setBackground(new java.awt.Color(255, 255, 255));
        panelarticulos.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        panelarticulos.setForeground(new java.awt.Color(204, 0, 0));
        panelarticulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelarticulosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelarticulosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelarticulosMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelarticulosMouseReleased(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Imagenes/respaldo - copia.PNG"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("  Importar");

        javax.swing.GroupLayout panelarticulosLayout = new javax.swing.GroupLayout(panelarticulos);
        panelarticulos.setLayout(panelarticulosLayout);
        panelarticulosLayout.setHorizontalGroup(
            panelarticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelarticulosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelarticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addGroup(panelarticulosLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelarticulosLayout.setVerticalGroup(
            panelarticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelarticulosLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlOperaciones.add(panelarticulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 120, -1, 136));

        panelcompras.setBackground(new java.awt.Color(255, 255, 255));
        panelcompras.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        panelcompras.setForeground(new java.awt.Color(204, 0, 0));
        panelcompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelcomprasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelcomprasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelcomprasMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelcomprasMouseReleased(evt);
            }
        });

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Imagenes/respaldo.PNG"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Respaldo");

        javax.swing.GroupLayout panelcomprasLayout = new javax.swing.GroupLayout(panelcompras);
        panelcompras.setLayout(panelcomprasLayout);
        panelcomprasLayout.setHorizontalGroup(
            panelcomprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelcomprasLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelcomprasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelcomprasLayout.setVerticalGroup(
            panelcomprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelcomprasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(7, 7, 7))
        );

        pnlOperaciones.add(panelcompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 118, -1, 138));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlOperaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlOperaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void panelgenerarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelgenerarMouseReleased
        
    }//GEN-LAST:event_panelgenerarMouseReleased

    private void panelgenerarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelgenerarMouseEntered
        panelgenerar.setBorder(new EtchedBorder(EtchedBorder.RAISED,Color.red,Color.black));
    }//GEN-LAST:event_panelgenerarMouseEntered

    private void panelgenerarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelgenerarMouseExited
        panelgenerar.setBorder(new EtchedBorder(EtchedBorder.RAISED,Color.white,Color.white));
    }//GEN-LAST:event_panelgenerarMouseExited

    private void panelarticulosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelarticulosMouseEntered
        panelarticulos.setBorder(new EtchedBorder(EtchedBorder.RAISED,Color.red,Color.black));
    }//GEN-LAST:event_panelarticulosMouseEntered

    private void panelarticulosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelarticulosMouseExited
        panelarticulos.setBorder(new EtchedBorder(EtchedBorder.RAISED,Color.white,Color.white));
    }//GEN-LAST:event_panelarticulosMouseExited

    private void panelarticulosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelarticulosMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_panelarticulosMouseReleased

    private void panelcomprasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelcomprasMouseEntered
        panelcompras.setBorder(new EtchedBorder(EtchedBorder.RAISED,Color.red,Color.black));
    }//GEN-LAST:event_panelcomprasMouseEntered

    private void panelcomprasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelcomprasMouseExited
        panelcompras.setBorder(new EtchedBorder(EtchedBorder.RAISED,Color.white,Color.white));
    }//GEN-LAST:event_panelcomprasMouseExited

    private void panelcomprasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelcomprasMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_panelcomprasMouseReleased

    private void panelgenerarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelgenerarMouseClicked
        pnlBarras barra=new pnlBarras();
        barra.setSize(640,570);
        barra.setLocation(0,0);
        
        pnlOperaciones.removeAll();
        pnlOperaciones.add(barra,BorderLayout.CENTER);
        pnlOperaciones.revalidate();
        pnlOperaciones.repaint();
    }//GEN-LAST:event_panelgenerarMouseClicked

    private void panelgenerarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelgenerarMousePressed
        
    }//GEN-LAST:event_panelgenerarMousePressed

    private void panelcomprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelcomprasMouseClicked
        if (!Template.Principal_Norm.info.getText().equals("USUARIO")) {
            GeneraBackup();
        }else{
            ErrorAlert a = new ErrorAlert(new JFrame(), true);
            a.titulo.setText("Sin acceso.");
            a.msj.setText("");
            a.msj1.setText("");
            a.setVisible(true);
        }
    }//GEN-LAST:event_panelcomprasMouseClicked

    private void panelarticulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelarticulosMouseClicked
       
    }//GEN-LAST:event_panelarticulosMouseClicked

    private void panelfacturaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelfacturaMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_panelfacturaMouseReleased

    private void panelfacturaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelfacturaMouseExited
        panelfactura.setBorder(new EtchedBorder(EtchedBorder.RAISED,Color.white,Color.white));
    }//GEN-LAST:event_panelfacturaMouseExited

    private void panelfacturaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelfacturaMouseEntered
        panelfactura.setBorder(new EtchedBorder(EtchedBorder.RAISED,Color.red,Color.black));
    }//GEN-LAST:event_panelfacturaMouseEntered
    private void GeneraBackup() {
        WarningBackup a = new WarningBackup(null, true);
        a.setVisible(true);

        if (a.txtNombre.getText().length() != 0) {
            new BackupMySQL().exportDB(a.txtNombre.getText());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel panelarticulos;
    private javax.swing.JPanel panelcompras;
    private javax.swing.JPanel panelfactura;
    private javax.swing.JPanel panelgenerar;
    private javax.swing.JPanel pnlOperaciones;
    // End of variables declaration//GEN-END:variables
}
